# EXPLORATORY DATA ANALYSIS

## 1. Importação das bibliotecas

In [ ]:
import pandas as pd

## 2. Criação dos dataframes baseado nos datasets

In [80]:
# dataframe dos clientes
df_customers = pd.read_csv('../data/churn_customers.csv')
df_customers.head(5)

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

In [81]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   object
 1   gender         7043 non-null   object
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   object
 4   Dependents     7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB

In [82]:
# dataframe dos serviços
df_services = pd.read_csv('../data/churn_services.csv')
df_services.head(5)

,customerID,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Yes,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Yes,No,Fiber optic,No,No,No,No,No,No

In [83]:
df_services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   PhoneService      7043 non-null   object
 2   MultipleLines     7043 non-null   object
 3   InternetService   7043 non-null   object
 4   OnlineSecurity    7043 non-null   object
 5   OnlineBackup      7043 non-null   object
 6   DeviceProtection  7043 non-null   object
 7   TechSupport       7043 non-null   object
 8   StreamingTV       7043 non-null   object
 9   StreamingMovies   7043 non-null   object
dtypes: object(10)
memory usage: 550.4+ KB

In [84]:
# dataframe dos contratos
df_contracts = pd.read_csv('../data/churn_contracts.csv')
df_contracts.head(5)

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [85]:
df_contracts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   tenure            7043 non-null   int64
 2   Contract          7043 non-null   object
 3   PaperlessBilling  7043 non-null   object
 4   PaymentMethod     7043 non-null   object
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7043 non-null   object
 7   Churn             7043 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 440.3+ KB

## 3. Transformação dos dados

In [86]:
# transforma a coluna 'TotalCharges' de string para float, utilizando astype
# df_contracts['TotalCharges'] = df_contracts['TotalCharges'].astype(float) # Gerou erro porque existem valores não numéricos na coluna

# transforma a coluna 'TotalCharges' de string para float, utilizando to_numeric
# df_contracts['TotalCharges'] = pd.to_numeric(df_contracts['TotalCharges']) # Gerou erro porque existem valores não numéricos na coluna

# transforma coluna 'TotalCharges' de string para float, utilizando to_numeric com erros='coerce'
df_contracts['TotalCharges'] = pd.to_numeric(df_contracts['TotalCharges'], errors='coerce') # Converte os valores não numéricos para Null

In [87]:
df_contracts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   tenure            7043 non-null   int64
 2   Contract          7043 non-null   object
 3   PaperlessBilling  7043 non-null   object
 4   PaymentMethod     7043 non-null   object
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7032 non-null   float64
 7   Churn             7043 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 440.3+ KB

## 4. Renomeação das colunas

In [88]:
# cria um novo dataframe com a coluna 'SeniorCitizen' como 'Above65yo', utilizando rename e dict
df_customers_new = df_customers.rename(columns={'SeniorCitizen': 'Above65yo'}) # renomeia a coluna 'SeniorCitizen' para 'Above65yo' no DataFrame df_customers
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   object
 1   gender         7043 non-null   object
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   object
 4   Dependents     7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB

In [89]:
# renomeia coluna 'SeniorCitizen' para 'Above65yo', utilizando rename e dict
df_customers.rename(columns={'SeniorCitizen': 'Above65yo'}, inplace=True)
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7043 non-null   object
 1   gender      7043 non-null   object
 2   Above65yo   7043 non-null   int64
 3   Partner     7043 non-null   object
 4   Dependents  7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB

In [90]:
df_customers.columns = ['CustomerID', 'Gender', 'Above65yo', 'Partner', 'Dependents'] # renomeia todas as colunas do DataFrame df_customers
df_customers.head(5)

   CustomerID  Gender  Above65yo Partner Dependents
0  7590-VHVEG  Female          0     Yes         No
1  5575-GNVDE    Male          0      No         No
2  3668-QPYBK    Male          0      No         No
3  7795-CFOCW    Male          0      No         No
4  9237-HQITU  Female          0      No         No

## 5. Unificando datasets

In [91]:
print(len(df_customers), len(df_services), len(df_contracts)) # garante que o número de linhas é o mesmo em todos os dataframes
df_services.rename(columns={'customerID': 'CustomerID'}, inplace=True) # renomeia coluna 'customerID' para 'CustomerId' em df_services para ficar com o mesmo nome em todos os dataframes

7043 7043 7043

In [92]:
df_temp = df_customers.merge(df_services, on='CustomerID') # faz um merge entre os dataframes df_customers e df_services, utilizando a coluna 'CustomerID' como chave
df_temp.head(5)

,CustomerID,Gender,Above65yo,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,Female,0,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Male,0,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Male,0,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,Male,0,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Female,0,No,No,Yes,No,Fiber optic,No,No,No,No,No,No

In [93]:
# Mergeando os dataframes df_temp e df_contracts, utilizando merge sem renomear a coluna 'customerID' para 'CustomerId'
df_churn_temp = df_temp.merge(df_contracts, left_on=['CustomerID'], right_on=['customerID'], how='inner')
df_churn_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        7043 non-null   object
 1   Gender            7043 non-null   object
 2   Above65yo         7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  customerID        7043 non-null   object
 15  tenure            7043 non-null   int64
 16  Contract          7043 non-null   object
 17  PaperlessBilling  7043 non-null   object
 18  PaymentMethod     7043 non-null   object
 19  MonthlyCharges    7043 non-null   float64
 20  TotalCharges      7032 non-null   float64
 21  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(18)
memory usage: 1.2+ MB

In [94]:
# unificar os três dataframes ao mesmo tempo, mesmo que eles tenham nomes de colunas diferentes 
df_churn = df_customers.merge(df_services, on='CustomerID').merge(df_contracts, left_on=['CustomerID'], right_on=['customerID']) 
df_churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        7043 non-null   object
 1   Gender            7043 non-null   object
 2   Above65yo         7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  customerID        7043 non-null   object
 15  tenure            7043 non-null   int64
 16  Contract          7043 non-null   object
 17  PaperlessBilling  7043 non-null   object
 18  PaymentMethod     7043 non-null   object
 19  MonthlyCharges    7043 non-null   float64
 20  TotalCharges      7032 non-null   float64
 21  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(18)
memory usage: 1.2+ MB

In [95]:
# Removendo a coluna repetida 'customerID' do DataFrame df_churn
df_churn.drop(columns=['customerID'], inplace=True) # mesmo que df_churn.drop(['customerID'], axis=1, inplace=True) axis=1 é o mesmo que axis='columns'
df_churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        7043 non-null   object
 1   Gender            7043 non-null   object
 2   Above65yo         7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  tenure            7043 non-null   int64
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB